services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    volumes:
      - ollama_models:/root/.ollama
    ports:
      - "11434:11434"
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 5
    entrypoint:
      [
        "bash",
        "-lc",
        "ollama serve & sleep 3 && ollama pull gemma3:latest && ollama pull embeddinggemma:latest && wait -n",
      ]

  api:
    build: .
    container_name: rag-api
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      OLLAMA_BASE_URL: http://ollama:11434
      EMBEDDING_MODEL: embeddinggemma
      GENERATION_MODEL: gemma3:latest
    volumes:
      - ./data:/app/data
    ports:
      - "3400:3400"
    command:
      [
        "uv",
        "run",
        "uvicorn",
        "src.api.app:app",
        "--host",
        "0.0.0.0",
        "--port",
        "3400",
      ]

volumes:
  ollama_models:
